### ISSUE TITLE
[BUG?]: Last Update broke my saved tabs

### ISSUE THREAD

**Issue by REIS0** [lbragile/TabMerger#25] opened 2021-02-06 16:46 UTC
Recent update in the extension deleted my saved tabs, I had about 5 groups with at least 20 tabs each.

I don't know how to reproduce it since it was working just yesterday. Maybe decreasing to a older version and then upgrading to the new version.

**Expected behavior**
My old tabs didn't get deleted.

As you can see there's only template tutorial tabs,
![image](https://user-images.githubusercontent.com/38042161/107124163-06025300-689a-11eb-9dcd-8ca33e26b69d.png)

- OS: Pop_OS! 20.10
- Browser Firefox
- Version 1.6.0

Not sure if this is exactly a bug since it can be a problem with my own system, but still was kinda surprised that it happened, luckily I think I have a backup somewhere.

**Comment by lbragile** [comment] 2021-02-06 20:15
@REIS0 Thank you for reporting the issue. I now see the root cause and will add more checks to eliminate this!

**Comment by lbragile** [comment] 2021-02-07 01:00
@REIS0 Just fixed in v1.6.1 and all tests still pass - let me know if there are other issues. Closing now!

**Closed by lbragile** 2021-02-07 01:00 UTC
Labels: bug
