### ISSUE TITLE
[FEATURE]: Keep the tab's state in memory: pinned or not, devtools opened or not.

### ISSUE THREAD

**Issue by FelDev** [lbragile/TabMerger#12] opened 2021-01-10 16:02 UTC
**Describe the solution you'd like**
When I "open group" or open a single tab, the tabs that were pinned are reopened as pinned.
If devtools was open when I last merged the tabs, devtools is opened again
Maybe similar things could be kept in memory about tabs' states; zoom level and whatnot.

Having pinned tabs reopen as pinned is what would be most valuable to me.

Thanks for this great extension!

**Comment by lbragile** [comment] 2021-01-10 20:17
Hi @FelDev,

This seems to be a duplicate of #6 with  additional twists (dev tools, zoom level, etc.).
I will have to take a look into these - thank you!

**Closed** 2022-01-12 07:12 UTC
Labels: duplicate
